apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protein-villa-db-pvc
  namespace: protein-villa
  labels:
    app: protein-villa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
